# Generated by Django 6.0.6 on 2026-08-10 12:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='album_covers/')),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('lyrics', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='music_covers/')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musics', to='music.album')),
            ],
        ),
        migrations.CreateModel(
            name='MusicArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_artists', to='accounts.artist')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_artists', to='music.music')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='artists',
            field=models.ManyToManyField(related_name='musics', through='music.MusicArtist', to='accounts.artist'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_musics', to='music.music')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_musics', to='music.playlist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(related_name='playlists', through='music.PlaylistMusic', to='music.music'),
        ),
        migrations.AddConstraint(
            model_name='musicartist',
            constraint=models.UniqueConstraint(fields=('music', 'artist'), name='unique_music_artist'),
        ),
        migrations.AddConstraint(
            model_name='playlistmusic',
            constraint=models.UniqueConstraint(fields=('playlist', 'music'), name='unique_music_in_playlist'),
        ),
        migrations.AddConstraint(
            model_name='playlistmusic',
            constraint=models.UniqueConstraint(fields=('playlist', 'position'), name='unique_playlist_position'),
        ),
    ]
