# Generated by Django 6.0.6 on 2026-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='albums/covers/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='tracks/audio/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tracks/covers/%Y/%m/'),
        ),
    ]
