# Generated by Django 6.0.6 on 2026-08-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_follow'),
        ('music', '0003_alter_album_cover_alter_music_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='accounts.artist'),
        ),
    ]
