# Generated by Django 6.0.6 on 2026-08-10 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_musics', to=settings.AUTH_USER_MODEL),
        ),
    ]
