# Generated by Django 6.0.6 on 2026-08-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='playlists/covers/%Y/%m/'),
        ),
    ]
