# Generated by Django 6.0.6 on 2026-08-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_playlist_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='collaborators',
            field=models.CharField(blank=True, help_text='Comma separated list of collaborating artists', max_length=255),
        ),
    ]
