# Generated by Django 6.0.6 on 2026-08-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
        ('music', '0007_music_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistMonthlySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_streams', models.PositiveIntegerField(default=0)),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='accounts.artist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('artist', 'month'), name='unique_artist_settlement_per_month')],
            },
        ),
    ]
