# Generated by Django 6.0.6 on 2026-08-16 14:24

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='شناسه یکتای اتاق که در لینک دعوت استفاده می\u200cشود', primary_key=True, serialize=False)),
                ('current_song', models.FileField(blank=True, help_text='فایل صوتی که آخرین بار در اتاق آپلود شده است', null=True, upload_to='room_songs/%Y/%m/%d/')),
                ('current_song_title', models.CharField(blank=True, default='', help_text='عنوان آهنگ فعلی', max_length=255)),
                ('current_position', models.FloatField(default=0.0, help_text='موقعیت پخش آهنگ به ثانیه')),
                ('is_playing', models.BooleanField(default=False, help_text='آیا آهنگ در حال پخش است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, help_text='کاربرانی که به این اتاق پیوسته\u200cاند', related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
